# Generated by Django 5.2.17 on 2026-09-27 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0002_alter_taferas_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Taferas',
            new_name='Tarefa',
        ),
    ]
